apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: jb1ay58p6-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.clusterpool-4xw8b.rhtap.devcluster.openshift.com/rhtap/rhtap-qe-java-quarkus:9d730ed6e9fc040d5092a76d1f9df288aa688834@sha256:3d8677fb32dea0ed34fa31dbc5a0424203deb4b309fb5f437bd39ebcf13d0bd5
        name: container-image  
